# config.yaml
model:
  name: <your-model-name>
  gcs_path: <your-model-gcs-path>
  version: "v1"

gcs:
   bucket_name: <your-model-bucket-name>
   dataset_name: <your-csv-data-name>
pipeline:
   name: <your-pipeline-name>
   description: <your-pipeline-description>
   pipeline_root: gs://<your-pipeline-gcs-path>"
service:
  image_uri: <gcloud-docker-artifact-path>
  service_name: <endpoint-service-name>
  region: <region>
  project_id: <project-id>
  min_instances: <min-instance-count>
  max_instances: <max-instance-count>
  concurrency: <max-concurrency-request-count>
  timeout: "60s"
